name: GPT AUTO REVIEW

on:
  pull_request:
    types: [opened, synchronize, labeled]

jobs:
  gpt-auto-review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: |
      ((github.event.action == 'labeled') && 
        (github.event.label.name == 'auto-review')) ||
      ((github.event.action == 'synchronize') &&
        contains(github.event.pull_request.labels.*.name, 'auto-review'))

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Get PR info
        run: |
          PR_URL=$(echo ${{ github.event.pull_request.url }})
          PR=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" $PR_URL)

          PR_TITLE=$(echo $PR | jq -r .title)
          PR_BODY=$(echo $PR | jq -r .body)
          PR_DIFF=$(git diff origin/${GITHUB_BASE_REF}...origin/${GITHUB_HEAD_REF})

          echo "# $PR_TITLE" >> PR_INFO.md
          echo $'## description\n'"$PR_BODY" >> PR_INFO.md
          printf '```diff%s\n%s\n%s```\n' "" "$PR_DIFF" "" >> PR_INFO.md

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Run gpt-auto-review
        env:
          GPT_API_KEY: ${{ secrets.GPT_API_KEY }}
        run: ./target/release/gpt-auto-review PR_INFO.md > PR_REVIEW.md

      - name: Post comments
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ github.event.pull_request.html_url }}
        run: gh pr comment -F PR_REVIEW.md "${URL}"
