name: 'GPT Auto Review'
description: 'Automatically review pull requests using GPT'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token for authentication'
    required: true
  GPT_API_KEY:
    description: 'API key for GPT'
    required: true
runs:
  using: 'composite'
  steps:
    - run: |
        PR_URL=$(echo ${{ github.event.pull_request.url }})
        PR=$(curl -s -H "Authorization: token ${{ inputs.GITHUB_TOKEN }}" $PR_URL)

        PR_TITLE=$(echo $PR | jq -r .title)
        PR_BODY=$(echo $PR | jq -r .body)
        PR_DIFF=$(git diff origin/${GITHUB_BASE_REF}...origin/${GITHUB_HEAD_REF})

        echo "# $PR_TITLE" >> PR_INFO.md
        echo $'## description\n'"$PR_BODY" >> PR_INFO.md
        printf '```diff%s\n%s\n%s```\n' "" "$PR_DIFF" "" >> PR_INFO.md
      shell: bash

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release

    - run: ./target/release/gpt-auto-review PR_INFO.md > PR_REVIEW.md
      env:
        GPT_API_KEY: ${{ inputs.GPT_API_KEY }}
      shell: bash

    - run: gh pr comment -F PR_REVIEW.md "${URL}"
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        URL: ${{ github.event.pull_request.html_url }}
      shell: bash
