name: My Workflow

on:
  pull_request:
    types: [opened, synchronize, labeled]

jobs:
  gpt-auto-review:
    runs-on: ubuntu-latest
    if: |
      ((github.event.action == 'labeled') && 
        (github.event.label.name == 'auto-review')) ||
      ((github.event.action == 'synchronize') &&
        contains(github.event.pull_request.labels.*.name, 'auto-review'))

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Get PR info
        run: |
          PR_URL=$(echo ${{ github.event.pull_request.url }})
          PR_INFO=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" $PR_URL)

          PR_TITLE=$(echo $PR_INFO | jq -r .title)
          PR_BODY=$(echo $PR_INFO | jq -r .body)

          echo "PR Title: $PR_TITLE"
          echo "PR Description: $PR_BODY"
      - name: Post Comment
        uses: github-actions-up-and-running/pr-comment@v1.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: 'test'
